CREATE TABLE TRANSACTION_ORDER (
   ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
   REQUEST_NO VARCHAR(255) NOT NULL DEFAULT '' COMMENT '业务请求流水号,用于幂等',
   BUSINESS_TYPE VARCHAR(255) NOT NULL DEFAULT '' COMMENT '业务类型',
   PAYER_ACCOUNT_NO VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出款方账户编号',
   PAYER_ACCOUNT_NAME VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出款方账户名称',
   PAYER_ORG_CODE VARCHAR(255) NOT NULL DEFAULT '' COMMENT '出款方机构编码',
   PAYEE_ACCOUNT_NO VARCHAR(255) NOT NULL DEFAULT '' COMMENT '收款方账户编号',
   PAYEE_ACCOUNT_NAME VARCHAR(255) NOT NULL DEFAULT '' COMMENT '收款方账户名称',
   PAYEE_ORG_CODE VARCHAR(255) NOT NULL DEFAULT '' COMMENT '收款方机构编码',
   AMOUNT DECIMAL(19,2) NOT NULL DEFAULT 0 COMMENT '交易金额',
   REMARK VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
   POSTSCRIPT VARCHAR(255) NOT NULL DEFAULT '' COMMENT '附言',
   STATUS INT NOT NULL DEFAULT 0 COMMENT '状态',
   GMT_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   GMT_UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
   CONSTRAINT UK_REQUEST_NO UNIQUE (REQUEST_NO)
);
